ALTER TABLE `listini` ADD COLUMN `tag` varchar(256) DEFAULT NULL;
update listini set tag=(select ta.tag from tipi_abbonamento ta where ta.id=id_tipo_abbonamento);

***

ALTER TABLE `tipi_abbonamento` DROP COLUMN `tag`;
ALTER TABLE `comunicazioni` ADD COLUMN `id_fascicolo_inizio` int(11) DEFAULT NULL;

***

RENAME TABLE cap TO localita;
ALTER TABLE `localita` CHANGE COLUMN `localita` `nome` varchar(64) NOT NULL;
ALTER TABLE `localita` ADD COLUMN `modifica_propagata` bit(0) default false;
ALTER TABLE `localita` ADD COLUMN `data_modifica` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;
UPDATE localita set data_modifica=CURRENT_TIMESTAMP;

***

ALTER TABLE `anagrafiche` ADD COLUMN `email_primaria_bounce` int(11) DEFAULT NULL;
ALTER TABLE `anagrafiche` DROP COLUMN `email_primaria_bounce`;
ALTER TABLE `anagrafiche` ADD COLUMN `search_string` varchar(256) DEFAULT NULL;

***

ALTER TABLE `pagamenti` CHANGE COLUMN `codice_abbonamento` `codice_abbonamento_match` varchar(16) NOT NULL;
ALTER TABLE `pagamenti` ADD COLUMN `codice_abbonamento_bollettino` varchar(16) DEFAULT NULL;

***

update anagrafiche set id_professione = null where id_professione = 28;
update anagrafiche set id_professione = null where id_professione = 31;
insert into professioni(id,nome) values (45,"Agente/Rappresentante");
insert into professioni(id,nome) values (46,"Agronomo");
insert into professioni(id,nome) values (47,"Archeologo");
insert into professioni(id,nome) values (48,"Assistente Sociale");
insert into professioni(id,nome) values (49,"Conservatore o Restauratore");
insert into professioni(id,nome) values (50,"Giornalista");
insert into professioni(id,nome) values (51,"Infermiere professionale");
insert into professioni(id,nome) values (52,"Psicoterapeuta");
insert into professioni(id,nome) values (53,"Ricercatore");
insert into professioni(id,nome) values (54,"Studente (non specifica)");
insert into professioni(id,nome) values (55,"Veterinario");
DROP TABLE IF EXISTS `titoli_studio`;
CREATE TABLE `titoli_studio` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `nome` varchar(64) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
insert into titoli_studio(id,nome) values (1,"Licenza elementare");
insert into titoli_studio(id,nome) values (2,"Licenza media");
insert into titoli_studio(id,nome) values (3,"Diploma");
insert into titoli_studio(id,nome) values (4,"Laurea");
insert into titoli_studio(id,nome) values (5,"Laurea + Master");
insert into titoli_studio(id,nome) values (6,"Dottorato/ricercatore");
ALTER TABLE `anagrafiche` ADD COLUMN `id_titolo_studio` int(11) DEFAULT NULL;
delete from professioni where id = 28;
delete from professioni where id = 31;

***

ALTER TABLE fatture ADD CONSTRAINT fatture_numero_fattura_unique UNIQUE (numero_fattura);

***

ALTER TABLE `opzioni` ADD COLUMN `codice` varchar(16) NOT NULL DEFAULT "";
UPDATE `opzioni` SET `codice`='M00' WHERE `id`=1;
UPDATE `opzioni` SET `codice`='M01' WHERE `id`=2;
UPDATE `opzioni` SET `codice`='M02' WHERE `id`=7;
UPDATE `opzioni` SET `codice`='M03' WHERE `id`=8;
UPDATE `opzioni` SET `codice`='M04' WHERE `id`=9;
UPDATE `opzioni` SET `codice`='M05' WHERE `id`=20;
UPDATE `opzioni` SET `codice`='M06' WHERE `id`=21;
UPDATE `opzioni` SET `codice`='M07' WHERE `id`=23;
UPDATE `opzioni` SET `codice`='M08' WHERE `id`=31;
UPDATE `opzioni` SET `codice`='M09' WHERE `id`=32;
UPDATE `opzioni` SET `codice`='M0A' WHERE `id`=33;
UPDATE `opzioni` SET `codice`='M0B' WHERE `id`=43;
UPDATE `opzioni` SET `codice`='M0C' WHERE `id`=44;
UPDATE `opzioni` SET `codice`='M0D' WHERE `id`=45;
UPDATE `opzioni` SET `codice`='M0E' WHERE `id`=56;
UPDATE `opzioni` SET `codice`='M0F' WHERE `id`=57;
UPDATE `opzioni` SET `codice`='M10' WHERE `id`=58;
UPDATE `opzioni` SET `codice`='A00' WHERE `id`=3;
UPDATE `opzioni` SET `codice`='A01' WHERE `id`=4;
UPDATE `opzioni` SET `codice`='A02' WHERE `id`=5;
UPDATE `opzioni` SET `codice`='A03' WHERE `id`=6;
UPDATE `opzioni` SET `codice`='A04' WHERE `id`=10;
UPDATE `opzioni` SET `codice`='A05' WHERE `id`=11;
UPDATE `opzioni` SET `codice`='A06' WHERE `id`=12;
UPDATE `opzioni` SET `codice`='A07' WHERE `id`=13;
UPDATE `opzioni` SET `codice`='A08' WHERE `id`=16;
UPDATE `opzioni` SET `codice`='A09' WHERE `id`=17;
UPDATE `opzioni` SET `codice`='A0A' WHERE `id`=18;
UPDATE `opzioni` SET `codice`='A0B' WHERE `id`=19;
UPDATE `opzioni` SET `codice`='D00' WHERE `id`=24;
UPDATE `opzioni` SET `codice`='D01' WHERE `id`=25;
UPDATE `opzioni` SET `codice`='A0C' WHERE `id`=26;
UPDATE `opzioni` SET `codice`='A0D' WHERE `id`=27;
UPDATE `opzioni` SET `codice`='A0E' WHERE `id`=29;
UPDATE `opzioni` SET `codice`='A0F' WHERE `id`=30;
UPDATE `opzioni` SET `codice`='D02' WHERE `id`=35;
UPDATE `opzioni` SET `codice`='D03' WHERE `id`=37;
UPDATE `opzioni` SET `codice`='A10' WHERE `id`=39;
UPDATE `opzioni` SET `codice`='A11' WHERE `id`=40;
UPDATE `opzioni` SET `codice`='A12' WHERE `id`=41;
UPDATE `opzioni` SET `codice`='A13' WHERE `id`=42;
UPDATE `opzioni` SET `codice`='D04' WHERE `id`=47;
UPDATE `opzioni` SET `codice`='D05' WHERE `id`=48;
UPDATE `opzioni` SET `codice`='D06' WHERE `id`=49;
UPDATE `opzioni` SET `codice`='A14' WHERE `id`=53;
UPDATE `opzioni` SET `codice`='A15' WHERE `id`=54;
UPDATE `opzioni` SET `codice`='A16' WHERE `id`=55;
UPDATE `opzioni` SET `codice`='D07' WHERE `id`=59;
UPDATE `opzioni` SET `codice`='D08' WHERE `id`=60;
UPDATE `opzioni` SET `codice`='D09' WHERE `id`=61;
ALTER TABLE `opzioni` ADD CONSTRAINT opzioni_codice_unique UNIQUE (codice);

***

update localita set cap='38092' where id_provincia='TN' and nome like 'FAVER';
update localita set cap='38092' where id_provincia='TN' and nome like 'GRAUNO';
update localita set cap='38092' where id_provincia='TN' and nome like 'GRUMES';
update localita set cap='38092' where id_provincia='TN' and nome like 'VALDA';
update localita set cap='38049' where id_provincia='TN' and nome like 'BOSENTINO';
update localita set cap='38049' where id_provincia='TN' and nome like 'CENTA SAN NICOLO\'';
update localita set cap='38049' where id_provincia='TN' and nome like 'VATTARO';
update localita set cap='38049' where id_provincia='TN' and nome like 'VIGOLO VATTARO';
update localita set cap='38011' where id_provincia='TN' and nome like 'AMBLAR';
update localita set cap='38011' where id_provincia='TN' and nome like 'DON';
update localita set cap='38083' where id_provincia='TN' and nome like 'BRIONE';
update localita set cap='38083' where id_provincia='TN' and nome like 'CIMEGO';
update localita set cap='38083' where id_provincia='TN' and nome like 'CONDINO';
update localita set cap='38079' where id_provincia='TN' and nome like 'BOLBENO';
update localita set cap='38079' where id_provincia='TN' and nome like 'ZUCLO';
update localita set cap='38059' where id_provincia='TN' and nome like 'SPERA';
update localita set cap='38059' where id_provincia='TN' and nome like 'STRIGNO';
update localita set cap='38059' where id_provincia='TN' and nome like 'VILLA AGNEDO';
update localita set cap='38034' where id_provincia='TN' and nome like 'CEMBRA';
update localita set cap='38034' where id_provincia='TN' and nome like 'LISIGNAGO';
update localita set cap='38093' where id_provincia='TN' and nome like 'CUNEVO';
update localita set cap='38093' where id_provincia='TN' and nome like 'FLAVON';
update localita set cap='38093' where id_provincia='TN' and nome like 'TERRES';
update localita set cap='38025' where id_provincia='TN' and nome like 'DIMARO';
update localita set cap='38025' where id_provincia='TN' and nome like 'MONCLASSICO';
update localita set cap='38076' where id_provincia='TN' and nome like 'SARCHE';
update localita set cap='38076' where id_provincia='TN' and nome like 'CALAVINO';
update localita set cap='38076' where id_provincia='TN' and nome like 'LASINO';
update localita set cap='38085' where id_provincia='TN' and nome like 'PIEVE DI BONO';
update localita set cap='38085' where id_provincia='TN' and nome like 'PREZZO';
update localita set cap='38094' where id_provincia='TN' and nome like 'IAVRE\'';
update localita set cap='38094' where id_provincia='TN' and nome like 'VERDESINA';
update localita set cap='38094' where id_provincia='TN' and nome like 'DARE\'';
update localita set cap='38094' where id_provincia='TN' and nome like 'VIGO RENDENA';
update localita set cap='38094' where id_provincia='TN' and nome like 'VILLA RENDENA';
update localita set cap='38054' where id_provincia='TN' and nome like 'FIERA DI PRIMIERO';
update localita set cap='38054' where id_provincia='TN' and nome like 'TONADICO';
update localita set cap='38054' where id_provincia='TN' and nome like 'TRANSACQUA';
update localita set cap='38054' where id_provincia='TN' and nome like 'SIROR';
update localita set cap='38087' where id_provincia='TN' and nome like 'BONDO';
update localita set cap='38087' where id_provincia='TN' and nome like 'BREGUZZO';
update localita set cap='38087' where id_provincia='TN' and nome like 'LARDARO';
update localita set cap='38087' where id_provincia='TN' and nome like 'RONCONE';
update localita set cap='38095' where id_provincia='TN' and nome like 'RAGOLI';
update localita set cap='38095' where id_provincia='TN' and nome like 'PREORE';
update localita set cap='38095' where id_provincia='TN' and nome like 'MONTAGNE';
update localita set cap='38096' where id_provincia='TN' and nome like 'MARGONE';
update localita set cap='38096' where id_provincia='TN' and nome like 'RANZO';
update localita set cap='38096' where id_provincia='TN' and nome like 'PADERGNONE';
update localita set cap='38096' where id_provincia='TN' and nome like 'TERLAGO';
update localita set cap='38096' where id_provincia='TN' and nome like 'VEZZANO';
update localita set cap='38019' where id_provincia='TN' and nome like 'NANNO';
update localita set cap='38019' where id_provincia='TN' and nome like 'TASSULLO';
update localita set cap='38019' where id_provincia='TN' and nome like 'TUENNO';
update localita set cap='28846' where id_provincia='VB' and nome like 'SEPPIANA';
update localita set cap='28846' where id_provincia='VB' and nome like 'VIGANELLA';
update localita set cap='13812' where id_provincia='BI' and nome like 'CAMPIGLIA CERVO';
update localita set cap='13812' where id_provincia='BI' and nome like 'QUITTENGO';
update localita set cap='13812' where id_provincia='BI' and nome like 'SAN PAOLO CERVO';
update localita set cap='13853' where id_provincia='BI' and nome like 'CROSA';
update localita set cap='13853' where id_provincia='BI' and nome like 'LESSONA';
update localita set cap='40046' where id_provincia='BO' and nome like 'BORGO CAPANNE';
update localita set cap='40046' where id_provincia='BO' and nome like 'CASA CALISTRI';
update localita set cap='40046' where id_provincia='BO' and nome like 'CASA FORLAI';
update localita set cap='40046' where id_provincia='BO' and nome like 'MOLINO DEL PALLONE';
update localita set cap='40046' where id_provincia='BO' and nome like 'PONTE DELLA VENTURINA';
update localita set cap='40046' where id_provincia='BO' and nome like 'VIZZERO';
update localita set cap='40046' where id_provincia='BO' and nome like 'GRANAGLIONE';
update localita set cap='40046' where id_provincia='BO' and nome like 'PORRETTA TERME';
update localita set cap='42032' where id_provincia='RE' and nome like 'CERRETO ALPI';
update localita set cap='42032' where id_provincia='RE' and nome like 'CINQUECERRI';
update localita set cap='42032' where id_provincia='RE' and nome like 'CASTAGNETO';
update localita set cap='42032' where id_provincia='RE' and nome like 'PIEVE SAN VINCENZO';
update localita set cap='42032' where id_provincia='RE' and nome like 'SUCCISO NUOVO';
update localita set cap='42032' where id_provincia='RE' and nome like 'BUSANA';
update localita set cap='42032' where id_provincia='RE' and nome like 'COLLAGNA';
update localita set cap='42032' where id_provincia='RE' and nome like 'LIGONCHIO';
update localita set cap='42032' where id_provincia='RE' and nome like 'RAMISETO';
update localita set cap='43016' where id_provincia='PR' and nome like 'PIEVEOTTOVILLE';
update localita set cap='43016' where id_provincia='PR' and nome like 'POLESINE PARMENSE';
update localita set cap='43016' where id_provincia='PR' and nome like 'ZIBELLO';
update localita set cap='47854' where id_provincia='RN' and nome like 'MONTESCUDO';
update localita set cap='47854' where id_provincia='RN' and nome like 'MONTE COLOMBO';
update localita set cap='27014' where id_provincia='PV' and nome like 'CORTEOLONA';
update localita set cap='27014' where id_provincia='PV' and nome like 'GENZONE';
update localita set cap='23020' where id_provincia='SO' and nome like 'GORDONA';
update localita set cap='23020' where id_provincia='SO' and nome like 'MENAROLA';
update indirizzi set cap='38092' where id_provincia='TN' and localita like 'FAVER';
update indirizzi set cap='38092' where id_provincia='TN' and localita like 'GRAUNO';
update indirizzi set cap='38092' where id_provincia='TN' and localita like 'GRUMES';
update indirizzi set cap='38092' where id_provincia='TN' and localita like 'VALDA';
update indirizzi set cap='38049' where id_provincia='TN' and localita like 'BOSENTINO';
update indirizzi set cap='38049' where id_provincia='TN' and localita like 'CENTA SAN NICOLO\'';
update indirizzi set cap='38049' where id_provincia='TN' and localita like 'VATTARO';
update indirizzi set cap='38049' where id_provincia='TN' and localita like 'VIGOLO VATTARO';
update indirizzi set cap='38011' where id_provincia='TN' and localita like 'AMBLAR';
update indirizzi set cap='38011' where id_provincia='TN' and localita like 'DON';
update indirizzi set cap='38083' where id_provincia='TN' and localita like 'BRIONE';
update indirizzi set cap='38083' where id_provincia='TN' and localita like 'CIMEGO';
update indirizzi set cap='38083' where id_provincia='TN' and localita like 'CONDINO';
update indirizzi set cap='38079' where id_provincia='TN' and localita like 'BOLBENO';
update indirizzi set cap='38079' where id_provincia='TN' and localita like 'ZUCLO';
update indirizzi set cap='38059' where id_provincia='TN' and localita like 'SPERA';
update indirizzi set cap='38059' where id_provincia='TN' and localita like 'STRIGNO';
update indirizzi set cap='38059' where id_provincia='TN' and localita like 'VILLA AGNEDO';
update indirizzi set cap='38034' where id_provincia='TN' and localita like 'CEMBRA';
update indirizzi set cap='38034' where id_provincia='TN' and localita like 'LISIGNAGO';
update indirizzi set cap='38093' where id_provincia='TN' and localita like 'CUNEVO';
update indirizzi set cap='38093' where id_provincia='TN' and localita like 'FLAVON';
update indirizzi set cap='38093' where id_provincia='TN' and localita like 'TERRES';
update indirizzi set cap='38025' where id_provincia='TN' and localita like 'DIMARO';
update indirizzi set cap='38025' where id_provincia='TN' and localita like 'MONCLASSICO';
update indirizzi set cap='38076' where id_provincia='TN' and localita like 'SARCHE';
update indirizzi set cap='38076' where id_provincia='TN' and localita like 'CALAVINO';
update indirizzi set cap='38076' where id_provincia='TN' and localita like 'LASINO';
update indirizzi set cap='38085' where id_provincia='TN' and localita like 'PIEVE DI BONO';
update indirizzi set cap='38085' where id_provincia='TN' and localita like 'PREZZO';
update indirizzi set cap='38094' where id_provincia='TN' and localita like 'IAVRE\'';
update indirizzi set cap='38094' where id_provincia='TN' and localita like 'VERDESINA';
update indirizzi set cap='38094' where id_provincia='TN' and localita like 'DARE\'';
update indirizzi set cap='38094' where id_provincia='TN' and localita like 'VIGO RENDENA';
update indirizzi set cap='38094' where id_provincia='TN' and localita like 'VILLA RENDENA';
update indirizzi set cap='38054' where id_provincia='TN' and localita like 'FIERA DI PRIMIERO';
update indirizzi set cap='38054' where id_provincia='TN' and localita like 'TONADICO';
update indirizzi set cap='38054' where id_provincia='TN' and localita like 'TRANSACQUA';
update indirizzi set cap='38054' where id_provincia='TN' and localita like 'SIROR';
update indirizzi set cap='38087' where id_provincia='TN' and localita like 'BONDO';
update indirizzi set cap='38087' where id_provincia='TN' and localita like 'BREGUZZO';
update indirizzi set cap='38087' where id_provincia='TN' and localita like 'LARDARO';
update indirizzi set cap='38087' where id_provincia='TN' and localita like 'RONCONE';
update indirizzi set cap='38095' where id_provincia='TN' and localita like 'RAGOLI';
update indirizzi set cap='38095' where id_provincia='TN' and localita like 'PREORE';
update indirizzi set cap='38095' where id_provincia='TN' and localita like 'MONTAGNE';
update indirizzi set cap='38096' where id_provincia='TN' and localita like 'MARGONE';
update indirizzi set cap='38096' where id_provincia='TN' and localita like 'RANZO';
update indirizzi set cap='38096' where id_provincia='TN' and localita like 'PADERGNONE';
update indirizzi set cap='38096' where id_provincia='TN' and localita like 'TERLAGO';
update indirizzi set cap='38096' where id_provincia='TN' and localita like 'VEZZANO';
update indirizzi set cap='38019' where id_provincia='TN' and localita like 'NANNO';
update indirizzi set cap='38019' where id_provincia='TN' and localita like 'TASSULLO';
update indirizzi set cap='38019' where id_provincia='TN' and localita like 'TUENNO';
update indirizzi set cap='28846' where id_provincia='VB' and localita like 'SEPPIANA';
update indirizzi set cap='28846' where id_provincia='VB' and localita like 'VIGANELLA';
update indirizzi set cap='13812' where id_provincia='BI' and localita like 'CAMPIGLIA CERVO';
update indirizzi set cap='13812' where id_provincia='BI' and localita like 'QUITTENGO';
update indirizzi set cap='13812' where id_provincia='BI' and localita like 'SAN PAOLO CERVO';
update indirizzi set cap='13853' where id_provincia='BI' and localita like 'CROSA';
update indirizzi set cap='13853' where id_provincia='BI' and localita like 'LESSONA';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'BORGO CAPANNE';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'CASA CALISTRI';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'CASA FORLAI';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'MOLINO DEL PALLONE';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'PONTE DELLA VENTURINA';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'VIZZERO';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'GRANAGLIONE';
update indirizzi set cap='40046' where id_provincia='BO' and localita like 'PORRETTA TERME';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'CERRETO ALPI';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'CINQUECERRI';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'CASTAGNETO';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'PIEVE SAN VINCENZO';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'SUCCISO NUOVO';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'BUSANA';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'COLLAGNA';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'LIGONCHIO';
update indirizzi set cap='42032' where id_provincia='RE' and localita like 'RAMISETO';
update indirizzi set cap='43016' where id_provincia='PR' and localita like 'PIEVEOTTOVILLE';
update indirizzi set cap='43016' where id_provincia='PR' and localita like 'POLESINE PARMENSE';
update indirizzi set cap='43016' where id_provincia='PR' and localita like 'ZIBELLO';
update indirizzi set cap='47854' where id_provincia='RN' and localita like 'MONTESCUDO';
update indirizzi set cap='47854' where id_provincia='RN' and localita like 'MONTE COLOMBO';
update indirizzi set cap='27014' where id_provincia='PV' and localita like 'CORTEOLONA';
update indirizzi set cap='27014' where id_provincia='PV' and localita like 'GENZONE';
update indirizzi set cap='23020' where id_provincia='SO' and localita like 'GORDONA';
update indirizzi set cap='23020' where id_provincia='SO' and localita like 'MENAROLA';
insert into localita set cap='38092', id_provincia='TN', nome='ALTAVALLE';
insert into localita set cap='38049', id_provincia='TN', nome='ALTOPIANO DELLA VIGOLANA';
insert into localita set cap='38011', id_provincia='TN', nome='AMBLAR-DON';
insert into localita set cap='38083', id_provincia='TN', nome='BORGO CHIESE';
insert into localita set cap='38079', id_provincia='TN', nome='BORGO LARES';
insert into localita set cap='38059', id_provincia='TN', nome='CASTEL IVANO';
insert into localita set cap='38034', id_provincia='TN', nome='CEMBRA LISIGNAGO';
insert into localita set cap='38093', id_provincia='TN', nome='CONTA\'';
insert into localita set cap='38025', id_provincia='TN', nome='DIMARO FOLGARIDA';
insert into localita set cap='38085', id_provincia='TN', nome='PIEVE DI BONO-PREZZO';
insert into localita set cap='38094', id_provincia='TN', nome='PORTE DI RENDENA';
insert into localita set cap='38054', id_provincia='TN', nome='PRIMIERO SAN MARTINO DI CASTROZZA';
insert into localita set cap='38087', id_provincia='TN', nome='SELLA GIUDICARIE';
insert into localita set cap='38095', id_provincia='TN', nome='TRE VILLE';
insert into localita set cap='38096', id_provincia='TN', nome='VALLELAGHI';
insert into localita set cap='38019', id_provincia='TN', nome='VILLE D\'ANAUNIA';
insert into localita set cap='28846', id_provincia='VB', nome='BORGOMEZZAVALLE';
insert into localita set cap='13812', id_provincia='BI', nome='CAMPIGLIA CERVO';
insert into localita set cap='13853', id_provincia='BI', nome='LESSONA';
insert into localita set cap='40046', id_provincia='BO', nome='ALTO RENO TERME';
insert into localita set cap='42032', id_provincia='RE', nome='VENTASSO';
insert into localita set cap='43016', id_provincia='PR', nome='POLESINE ZIBELLO';
insert into localita set cap='47854', id_provincia='RN', nome='MONTESCUDO - MONTE COLOMBO';
insert into localita set cap='27014', id_provincia='PV', nome='CORTEOLONA E GENZONE';
insert into localita set cap='23020', id_provincia='SO', nome='GORDONA';

***

ALTER TABLE `istanze_abbonamenti` ADD COLUMN `data_sync_mailing` DATETIME DEFAULT '1970-01-01 00:00:01' NOT NULL;

***

ALTER TABLE `societa` ADD COLUMN `prefisso_fatture_cartacee` varchar(8) DEFAULT NULL;
update societa set prefisso_fatture_cartacee='FXE' where id='GE';
update societa set prefisso_fatture_cartacee='FXS' where id='GS';

***

ALTER TABLE `listini` ADD COLUMN `codice` varchar(8) DEFAULT NULL;
CREATE INDEX listiniCodiceIdx ON listini (codice);
update listini set codice = "01003E" where id = "62";
update listini set codice = "04003F" where id = "63";
update listini set codice = "050040" where id = "64";
update listini set codice = "060041" where id = "65";
update listini set codice = "070042" where id = "66";
update listini set codice = "07013A" where id = "314";
update listini set codice = "090043" where id = "67";
update listini set codice = "0E0044" where id = "68";
update listini set codice = "PY0045" where id = "69";
update listini set codice = "PY0046" where id = "70";
update listini set codice = "180047" where id = "71";
update listini set codice = "18013E" where id = "318";
update listini set codice = "DP004A" where id = "74";
update listini set codice = "FN004B" where id = "75";
update listini set codice = "FT004C" where id = "76";
update listini set codice = "01004D" where id = "77";
update listini set codice = "PE004E" where id = "78";
update listini set codice = "PE0142" where id = "322";
update listini set codice = "PK004F" where id = "79";
update listini set codice = "PX0050" where id = "80";
update listini set codice = "B10051" where id = "81";
update listini set codice = "0L0052" where id = "82";
update listini set codice = "2L0053" where id = "83";
update listini set codice = "3L0054" where id = "84";
update listini set codice = "2E0055" where id = "85";
update listini set codice = "3E0056" where id = "86";
update listini set codice = "PW0057" where id = "87";
update listini set codice = "PY0058" where id = "88";
update listini set codice = "010059" where id = "89";
update listini set codice = "B1005A" where id = "90";
update listini set codice = "040075" where id = "117";
update listini set codice = "05005D" where id = "93";
update listini set codice = "09005E" where id = "94";
update listini set codice = "0E005F" where id = "95";
update listini set codice = "0L0060" where id = "96";
update listini set codice = "PY0061" where id = "97";
update listini set codice = "070062" where id = "98";
update listini set codice = "07013B" where id = "315";
update listini set codice = "180063" where id = "99";
update listini set codice = "18013F" where id = "319";
update listini set codice = "2E0064" where id = "100";
update listini set codice = "2L0065" where id = "101";
update listini set codice = "3E0066" where id = "102";
update listini set codice = "PZ0067" where id = "103";
update listini set codice = "PZ0147" where id = "327";
update listini set codice = "3L0068" where id = "104";
update listini set codice = "DP0069" where id = "105";
update listini set codice = "FN006A" where id = "106";
update listini set codice = "FT006B" where id = "107";
update listini set codice = "B1006C" where id = "108";
update listini set codice = "PE006D" where id = "109";
update listini set codice = "PE0143" where id = "323";
update listini set codice = "PK006E" where id = "110";
update listini set codice = "PW006F" where id = "111";
update listini set codice = "PX0070" where id = "112";
update listini set codice = "PY0071" where id = "113";
update listini set codice = "090072" where id = "114";
update listini set codice = "090073" where id = "115";
update listini set codice = "090074" where id = "116";
update listini set codice = "200077" where id = "119";
update listini set codice = "PZ0078" where id = "120";
update listini set codice = "PZ0146" where id = "326";
update listini set codice = "01007A" where id = "122";
update listini set codice = "01012D" where id = "301";
update listini set codice = "01015B" where id = "347";
update listini set codice = "010182" where id = "386";
update listini set codice = "0101AA" where id = "426";
update listini set codice = "0101D9" where id = "473";
update listini set codice = "0L007B" where id = "123";
update listini set codice = "0L0165" where id = "357";
update listini set codice = "0L01AF" where id = "431";
update listini set codice = "0L01DE" where id = "478";
update listini set codice = "03007C" where id = "124";
update listini set codice = "05007D" where id = "125";
update listini set codice = "05012B" where id = "299";
update listini set codice = "05015C" where id = "348";
update listini set codice = "050181" where id = "385";
update listini set codice = "0501AB" where id = "427";
update listini set codice = "0501DA" where id = "474";
update listini set codice = "0R007E" where id = "126";
update listini set codice = "0R0166" where id = "358";
update listini set codice = "0R01B0" where id = "432";
update listini set codice = "0R01DF" where id = "479";
update listini set codice = "09007F" where id = "127";
update listini set codice = "09015E" where id = "350";
update listini set codice = "090180" where id = "384";
update listini set codice = "0901AD" where id = "429";
update listini set codice = "0901DC" where id = "476";
update listini set codice = "090080" where id = "128";
update listini set codice = "090081" where id = "129";
update listini set codice = "090082" where id = "130";
update listini set codice = "0E0083" where id = "131";
update listini set codice = "0E015F" where id = "351";
update listini set codice = "0E0189" where id = "393";
update listini set codice = "0E01AE" where id = "430";
update listini set codice = "0E01DD" where id = "477";
update listini set codice = "2E0084" where id = "132";
update listini set codice = "2E0160" where id = "352";
update listini set codice = "2E018A" where id = "394";
update listini set codice = "2E01B2" where id = "434";
update listini set codice = "2E01E1" where id = "481";
update listini set codice = "3E0085" where id = "133";
update listini set codice = "3E0161" where id = "353";
update listini set codice = "3E018B" where id = "395";
update listini set codice = "3E01B4" where id = "436";
update listini set codice = "3E01E2" where id = "482";
update listini set codice = "18008A" where id = "138";
update listini set codice = "180167" where id = "359";
update listini set codice = "1801B1" where id = "433";
update listini set codice = "1801E0" where id = "480";
update listini set codice = "2L008D" where id = "141";
update listini set codice = "2L0168" where id = "360";
update listini set codice = "2L01B3" where id = "435";
update listini set codice = "2L01E3" where id = "483";
update listini set codice = "3L0090" where id = "144";
update listini set codice = "3L0169" where id = "361";
update listini set codice = "3L01B5" where id = "437";
update listini set codice = "3L01E4" where id = "484";
update listini set codice = "DP0091" where id = "145";
update listini set codice = "DP012C" where id = "300";
update listini set codice = "DP0162" where id = "354";
update listini set codice = "DP017E" where id = "382";
update listini set codice = "DP01B9" where id = "441";
update listini set codice = "DP01E8" where id = "488";
update listini set codice = "FN0092" where id = "146";
update listini set codice = "FT0093" where id = "147";
update listini set codice = "BR0094" where id = "148";
update listini set codice = "010095" where id = "149";
update listini set codice = "01012E" where id = "302";
update listini set codice = "050096" where id = "150";
update listini set codice = "05012F" where id = "303";
update listini set codice = "090097" where id = "151";
update listini set codice = "090099" where id = "153";
update listini set codice = "09009A" where id = "154";
update listini set codice = "09009B" where id = "155";
update listini set codice = "0E009C" where id = "156";
update listini set codice = "0L009D" where id = "157";
update listini set codice = "0R009E" where id = "158";
update listini set codice = "18009F" where id = "159";
update listini set codice = "2E00A0" where id = "160";
update listini set codice = "3E00A1" where id = "161";
update listini set codice = "2L00A2" where id = "162";
update listini set codice = "3L00A3" where id = "163";
update listini set codice = "DP00A4" where id = "164";
update listini set codice = "FN00A5" where id = "165";
update listini set codice = "FT00A6" where id = "166";
update listini set codice = "0100A7" where id = "167";
update listini set codice = "010129" where id = "297";
update listini set codice = "010151" where id = "337";
update listini set codice = "01017D" where id = "381";
update listini set codice = "010198" where id = "408";
update listini set codice = "0101EB" where id = "491";
update listini set codice = "0300A8" where id = "168";
update listini set codice = "0500A9" where id = "169";
update listini set codice = "050128" where id = "296";
update listini set codice = "050152" where id = "338";
update listini set codice = "05017C" where id = "380";
update listini set codice = "050199" where id = "409";
update listini set codice = "0501EC" where id = "492";
update listini set codice = "0900AA" where id = "170";
update listini set codice = "090154" where id = "340";
update listini set codice = "09017B" where id = "379";
update listini set codice = "09019B" where id = "411";
update listini set codice = "0901EE" where id = "494";
update listini set codice = "0900AB" where id = "171";
update listini set codice = "0900AC" where id = "172";
update listini set codice = "0900AD" where id = "173";
update listini set codice = "0E00AE" where id = "174";
update listini set codice = "0E0155" where id = "341";
update listini set codice = "0E0184" where id = "388";
update listini set codice = "0E019C" where id = "412";
update listini set codice = "0E01EF" where id = "495";
update listini set codice = "0L00AF" where id = "175";
update listini set codice = "0L016C" where id = "364";
update listini set codice = "0L019D" where id = "413";
update listini set codice = "0L01F0" where id = "496";
update listini set codice = "0R00B0" where id = "176";
update listini set codice = "0R016B" where id = "363";
update listini set codice = "0R019E" where id = "414";
update listini set codice = "0R01F1" where id = "497";
update listini set codice = "1800B1" where id = "177";
update listini set codice = "18016D" where id = "365";
update listini set codice = "18019F" where id = "415";
update listini set codice = "1801F2" where id = "498";
update listini set codice = "2E00B2" where id = "178";
update listini set codice = "2E0156" where id = "342";
update listini set codice = "2E0185" where id = "389";
update listini set codice = "2E01A0" where id = "416";
update listini set codice = "2E01F3" where id = "499";
update listini set codice = "2L00B3" where id = "179";
update listini set codice = "2L016E" where id = "366";
update listini set codice = "2L01A1" where id = "417";
update listini set codice = "2L01F4" where id = "500";
update listini set codice = "3E00B4" where id = "180";
update listini set codice = "3E0157" where id = "343";
update listini set codice = "3E0186" where id = "390";
update listini set codice = "3E01A2" where id = "418";
update listini set codice = "3E01F5" where id = "501";
update listini set codice = "3L00B5" where id = "181";
update listini set codice = "3L016F" where id = "367";
update listini set codice = "3L01A3" where id = "419";
update listini set codice = "3L01F7" where id = "503";
update listini set codice = "BR00B6" where id = "182";
update listini set codice = "DP00B7" where id = "183";
update listini set codice = "DP012A" where id = "298";
update listini set codice = "DP0159" where id = "345";
update listini set codice = "DP017A" where id = "378";
update listini set codice = "DP01A7" where id = "423";
update listini set codice = "DP01FA" where id = "506";
update listini set codice = "FN00B8" where id = "184";
update listini set codice = "FT00B9" where id = "185";
update listini set codice = "0100BA" where id = "186";
update listini set codice = "0200BB" where id = "187";
update listini set codice = "0500BC" where id = "188";
update listini set codice = "0900BD" where id = "189";
update listini set codice = "0901BE" where id = "446";
update listini set codice = "0900BE" where id = "190";
update listini set codice = "1800BF" where id = "191";
update listini set codice = "180141" where id = "321";
update listini set codice = "180173" where id = "371";
update listini set codice = "1801C2" where id = "450";
update listini set codice = "DP00C0" where id = "192";
update listini set codice = "DP0177" where id = "375";
update listini set codice = "DP01C7" where id = "455";
update listini set codice = "0900C1" where id = "193";
update listini set codice = "0900C2" where id = "194";
update listini set codice = "0E00C3" where id = "195";
update listini set codice = "0E01BF" where id = "447";
update listini set codice = "0L00C4" where id = "196";
update listini set codice = "0L0174" where id = "372";
update listini set codice = "0L01C0" where id = "448";
update listini set codice = "2E00C5" where id = "197";
update listini set codice = "2E01C3" where id = "451";
update listini set codice = "2L00C6" where id = "198";
update listini set codice = "2L0175" where id = "373";
update listini set codice = "2L01C4" where id = "452";
update listini set codice = "3E00C7" where id = "199";
update listini set codice = "3E01C5" where id = "453";
update listini set codice = "3L00C8" where id = "200";
update listini set codice = "3L0176" where id = "374";
update listini set codice = "3L01C6" where id = "454";
update listini set codice = "FN00C9" where id = "201";
update listini set codice = "FT00CA" where id = "202";
update listini set codice = "PK00CB" where id = "203";
update listini set codice = "PK01CA" where id = "458";
update listini set codice = "PX00CC" where id = "204";
update listini set codice = "PX0195" where id = "405";
update listini set codice = "PX01CB" where id = "459";
update listini set codice = "PY00CD" where id = "205";
update listini set codice = "PY01CC" where id = "460";
update listini set codice = "PZ00CE" where id = "206";
update listini set codice = "PZ0149" where id = "329";
update listini set codice = "PZ01CE" where id = "462";
update listini set codice = "0700CF" where id = "207";
update listini set codice = "07013D" where id = "317";
update listini set codice = "0701BD" where id = "445";
update listini set codice = "0400D0" where id = "208";
update listini set codice = "PE00D1" where id = "209";
update listini set codice = "PE0145" where id = "325";
update listini set codice = "PE01C9" where id = "457";
update listini set codice = "0900D2" where id = "210";
update listini set codice = "0900D3" where id = "211";
update listini set codice = "0900D4" where id = "212";
update listini set codice = "0100D5" where id = "213";
update listini set codice = "0400D6" where id = "214";
update listini set codice = "0700D7" where id = "215";
update listini set codice = "07013C" where id = "316";
update listini set codice = "0900D8" where id = "216";
update listini set codice = "0900D9" where id = "217";
update listini set codice = "0900DA" where id = "218";
update listini set codice = "0900DB" where id = "219";
update listini set codice = "0E00DC" where id = "220";
update listini set codice = "0L00DD" where id = "221";
update listini set codice = "1800DE" where id = "222";
update listini set codice = "180140" where id = "320";
update listini set codice = "2E00DF" where id = "223";
update listini set codice = "2L00E0" where id = "224";
update listini set codice = "3E00E1" where id = "225";
update listini set codice = "3L00E2" where id = "226";
update listini set codice = "DP00E3" where id = "227";
update listini set codice = "FN00E4" where id = "228";
update listini set codice = "FT00E5" where id = "229";
update listini set codice = "PE00E6" where id = "230";
update listini set codice = "PE0144" where id = "324";
update listini set codice = "PW00E7" where id = "231";
update listini set codice = "PX00E8" where id = "232";
update listini set codice = "PK00E9" where id = "233";
update listini set codice = "PY00EA" where id = "234";
update listini set codice = "PZ00EB" where id = "235";
update listini set codice = "PZ0148" where id = "328";
update listini set codice = "B100EC" where id = "236";
update listini set codice = "2000ED" where id = "237";
update listini set codice = "200172" where id = "370";
update listini set codice = "0400EE" where id = "238";
update listini set codice = "0700EF" where id = "239";
update listini set codice = "0900F0" where id = "240";
update listini set codice = "0900F1" where id = "241";
update listini set codice = "0900F2" where id = "242";
update listini set codice = "0900F3" where id = "243";
update listini set codice = "0E00F4" where id = "244";
update listini set codice = "0L00F5" where id = "245";
update listini set codice = "1800F6" where id = "246";
update listini set codice = "2E00F7" where id = "247";
update listini set codice = "2L00F8" where id = "248";
update listini set codice = "3E00F9" where id = "249";
update listini set codice = "3L00FA" where id = "250";
update listini set codice = "DP00FB" where id = "251";
update listini set codice = "FN00FC" where id = "252";
update listini set codice = "PX00FD" where id = "253";
update listini set codice = "FT00FE" where id = "254";
update listini set codice = "PK00FF" where id = "255";
update listini set codice = "PW0100" where id = "256";
update listini set codice = "PY0101" where id = "257";
update listini set codice = "PZ0102" where id = "258";
update listini set codice = "PE0103" where id = "259";
update listini set codice = "020104" where id = "260";
update listini set codice = "010105" where id = "261";
update listini set codice = "180106" where id = "262";
update listini set codice = "090107" where id = "263";
update listini set codice = "090108" where id = "264";
update listini set codice = "090109" where id = "265";
update listini set codice = "09010A" where id = "266";
update listini set codice = "FT010B" where id = "267";
update listini set codice = "0L010C" where id = "268";
update listini set codice = "PE010D" where id = "269";
update listini set codice = "0E010E" where id = "270";
update listini set codice = "PY0110" where id = "272";
update listini set codice = "2E0111" where id = "273";
update listini set codice = "3E0112" where id = "274";
update listini set codice = "2L0113" where id = "275";
update listini set codice = "3L0114" where id = "276";
update listini set codice = "DP0115" where id = "277";
update listini set codice = "FN0116" where id = "278";
update listini set codice = "PX0117" where id = "279";
update listini set codice = "PK0118" where id = "280";
update listini set codice = "PY0119" where id = "281";
update listini set codice = "PY011A" where id = "282";
update listini set codice = "PY011B" where id = "283";
update listini set codice = "PY01CD" where id = "461";
update listini set codice = "10011C" where id = "284";
update listini set codice = "02011D" where id = "285";
update listini set codice = "PX011E" where id = "286";
update listini set codice = "PX011F" where id = "287";
update listini set codice = "PX0120" where id = "288";
update listini set codice = "PX0121" where id = "289";
update listini set codice = "TV0122" where id = "290";
update listini set codice = "SC0123" where id = "291";
update listini set codice = "050124" where id = "292";
update listini set codice = "050153" where id = "339";
update listini set codice = "050183" where id = "387";
update listini set codice = "05019A" where id = "410";
update listini set codice = "0501ED" where id = "493";
update listini set codice = "050125" where id = "293";
update listini set codice = "05015D" where id = "349";
update listini set codice = "050188" where id = "392";
update listini set codice = "0501AC" where id = "428";
update listini set codice = "0501DB" where id = "475";
update listini set codice = "020126" where id = "294";
update listini set codice = "020127" where id = "295";
update listini set codice = "D10130" where id = "304";
update listini set codice = "D10158" where id = "344";
update listini set codice = "D10179" where id = "377";
update listini set codice = "D101A4" where id = "420";
update listini set codice = "D101F6" where id = "502";
update listini set codice = "PX0131" where id = "305";
update listini set codice = "PX015A" where id = "346";
update listini set codice = "PX0187" where id = "391";
update listini set codice = "PX01A9" where id = "425";
update listini set codice = "PX01FC" where id = "508";
update listini set codice = "PX0132" where id = "306";
update listini set codice = "PX0163" where id = "355";
update listini set codice = "PX018C" where id = "396";
update listini set codice = "PX01BB" where id = "443";
update listini set codice = "PX01EA" where id = "490";
update listini set codice = "ST0133" where id = "307";
update listini set codice = "0R0134" where id = "308";
update listini set codice = "0R01C1" where id = "449";
update listini set codice = "TV0135" where id = "309";
update listini set codice = "TV0136" where id = "310";
update listini set codice = "US0137" where id = "311";
update listini set codice = "D10138" where id = "312";
update listini set codice = "D10139" where id = "313";
update listini set codice = "LB014A" where id = "330";
update listini set codice = "LB014B" where id = "331";
update listini set codice = "LB014C" where id = "332";
update listini set codice = "LB014D" where id = "333";
update listini set codice = "LB01C8" where id = "456";
update listini set codice = "LB014E" where id = "334";
update listini set codice = "LB0170" where id = "368";
update listini set codice = "LB01A8" where id = "424";
update listini set codice = "LB01FB" where id = "507";
update listini set codice = "LB014F" where id = "335";
update listini set codice = "LB016A" where id = "362";
update listini set codice = "LB01BA" where id = "442";
update listini set codice = "LB01E9" where id = "489";
update listini set codice = "LB0150" where id = "336";
update listini set codice = "D10164" where id = "356";
update listini set codice = "D1017F" where id = "383";
update listini set codice = "D101B6" where id = "438";
update listini set codice = "D101E5" where id = "485";
update listini set codice = "TV0171" where id = "369";
update listini set codice = "TV01CF" where id = "463";
update listini set codice = "010178" where id = "376";
update listini set codice = "0101BC" where id = "444";
update listini set codice = "D1018D" where id = "397";
update listini set codice = "D9018E" where id = "398";
update listini set codice = "D901A5" where id = "421";
update listini set codice = "D901F8" where id = "504";
update listini set codice = "D9018F" where id = "399";
update listini set codice = "D901B7" where id = "439";
update listini set codice = "D901E6" where id = "486";
update listini set codice = "DE0190" where id = "400";
update listini set codice = "DE0191" where id = "401";
update listini set codice = "DE0192" where id = "402";
update listini set codice = "DE01A6" where id = "422";
update listini set codice = "DE01F9" where id = "505";
update listini set codice = "DE0193" where id = "403";
update listini set codice = "DE0194" where id = "404";
update listini set codice = "DE01B8" where id = "440";
update listini set codice = "DE01E7" where id = "487";
update listini set codice = "R10196" where id = "406";
update listini set codice = "R10197" where id = "407";
update listini set codice = "R101D0" where id = "464";
update listini set codice = "R101D1" where id = "465";
update listini set codice = "CV01D2" where id = "466";
update listini set codice = "CV01D3" where id = "467";
update listini set codice = "0101D4" where id = "468";
update listini set codice = "0501D5" where id = "469";
update listini set codice = "0901D6" where id = "470";
update listini set codice = "0R01D7" where id = "471";
update listini set codice = "PX01D8" where id = "472";
update listini set codice = "DX01FD" where id = "509";
update listini set codice = "DX01FE" where id = "510";
update listini set codice = "DX01FF" where id = "511";
update listini set codice = "DX0200" where id = "512";
update listini set codice = "DX0201" where id = "513";
update listini set codice = "180202" where id = "514";
ALTER TABLE listini ADD CONSTRAINT `listini_codice_key` UNIQUE (`codice`);

