package it.giunti.apg.automation.sap;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.giunti.apg.soap.anagmat.STOCKREPORTOUT;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-27T16:16:37.218+02:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "STOCK_REPORT_OUTService",
                  wsdlLocation = "/wsdl/IF_017_003_anagmat.wsdl",
                  targetNamespace = "urn:giuntieditore.com:3RD_PARTY:0090_STOCK_REPORT_ABB")
public class AnagmatSapService extends Service {

	public final static String WSDL_FILE_LOCATION = "/wsdl/IF_017_003_anagmat.wsdl";
    public final static URL WSDL_LOCATION = new FatteleSapServiceBusiness().getClass().getResource(WSDL_FILE_LOCATION);

    public final static QName SERVICE = new QName("urn:giuntieditore.com:3RD_PARTY:0090_STOCK_REPORT_ABB", "STOCK_REPORT_OUTService");
    public final static QName HTTPSPort = new QName("urn:giuntieditore.com:3RD_PARTY:0090_STOCK_REPORT_ABB", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:giuntieditore.com:3RD_PARTY:0090_STOCK_REPORT_ABB", "HTTP_Port");

    public AnagmatSapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AnagmatSapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AnagmatSapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public AnagmatSapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AnagmatSapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AnagmatSapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns STOCKREPORTOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public STOCKREPORTOUT getHTTPSPort() {
        return super.getPort(HTTPSPort, STOCKREPORTOUT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STOCKREPORTOUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public STOCKREPORTOUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, STOCKREPORTOUT.class, features);
    }


    /**
     *
     * @return
     *     returns STOCKREPORTOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public STOCKREPORTOUT getHTTPPort() {
        return super.getPort(HTTPPort, STOCKREPORTOUT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns STOCKREPORTOUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public STOCKREPORTOUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, STOCKREPORTOUT.class, features);
    }

}
