package it.giunti.apg.automation.sap;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

import it.giunti.apg.soap.creaodv.ORDEROUT;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-08-28T11:49:07.348+02:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "ORDER_OUTService",
                  wsdlLocation = "/wsdl/IF_017_001_creaodv.wsdl",
                  targetNamespace = "urn:giuntieditore.com:INTERNAL:0031_REPORT_ODV_ABB")
public class CreaodvSapService extends Service {

	public final static String WSDL_FILE_LOCATION = "/wsdl/IF_017_001_creaodv.wsdl";
    public final static URL WSDL_LOCATION = new FatteleSapServiceBusiness().getClass().getResource(WSDL_FILE_LOCATION);

    public final static QName SERVICE = new QName("urn:giuntieditore.com:INTERNAL:0031_REPORT_ODV_ABB", "ORDER_OUTService");
    public final static QName HTTPSPort = new QName("urn:giuntieditore.com:INTERNAL:0031_REPORT_ODV_ABB", "HTTPS_Port");
    public final static QName HTTPPort = new QName("urn:giuntieditore.com:INTERNAL:0031_REPORT_ODV_ABB", "HTTP_Port");
    

    public CreaodvSapService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CreaodvSapService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CreaodvSapService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public CreaodvSapService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public CreaodvSapService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public CreaodvSapService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ORDEROUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ORDEROUT getHTTPSPort() {
        return super.getPort(HTTPSPort, ORDEROUT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ORDEROUT
     */
    @WebEndpoint(name = "HTTPS_Port")
    public ORDEROUT getHTTPSPort(WebServiceFeature... features) {
        return super.getPort(HTTPSPort, ORDEROUT.class, features);
    }


    /**
     *
     * @return
     *     returns ORDEROUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public ORDEROUT getHTTPPort() {
        return super.getPort(HTTPPort, ORDEROUT.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ORDEROUT
     */
    @WebEndpoint(name = "HTTP_Port")
    public ORDEROUT getHTTPPort(WebServiceFeature... features) {
        return super.getPort(HTTPPort, ORDEROUT.class, features);
    }

}
